#database example

development:
  adapter: postgresql
  encoding: unicode
  database: project_development
  url: <%= ENV['DATABASE_URL'] %>

test:
  adapter: postgresql
  encoding: unicode
  database: project_test
  url: <%= ENV['DATABASE_URL'] %>

production:
  adapter: postgresql
  encoding: unicode
  database: project_production
  url: <%= ENV['DATABASE_URL'] %>
