
#database example

development:
  adapter: postgresql
  encoding: unicode
  database: project_development
  username: postgres
  password: postgres
  host: project-db.internal
  port: 0000

test:
  adapter: postgresql
  encoding: unicode
  database: project_test
  username: postgres
  password: postgres
  host: project-db.internal
  port: 0000

production:
  adapter: postgresql
  encoding: unicode
  database: project_production
  username: postgres
  password: postgres
  host: project-db.internal
  port: 0000
