development:
  adapter: postgresql
  encoding: unicode
  database: cars_management_rails_development
  username: postgres
  password: piOw8HyqoFUo9Sz
  host: cars-management-rails-db.internal
  port: 5432

test:
  adapter: postgresql
  encoding: unicode
  database: cars_management_rails_test
  username: postgres
  password: piOw8HyqoFUo9Sz
  host: cars-management-rails-db.internal
  port: 5432

production:
  adapter: postgresql
  encoding: unicode
  database: cars_management_rails_production
  username: postgres
  password: piOw8HyqoFUo9Sz
  host: cars-management-rails-db.internal
  port: 5432
