rails default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  port: 5432
  pool: 5
  username: postgres
  password: postgres

test:
  <<: *default
  database: cars_management_rails_test

development:
  <<: *default
  database: cars_management_rails_development

production:
  <<: *default
  database: cars_management_rails_production
